title: TEST
# email: 
# description:
url: "https://danielmiao1.github.io/local-github-site-test/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username:
# github_username:
theme: minima
plugins:
  - jekyll-feed
